### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by Ca7iburn** [MadCoder253/GCA5Roll20Exporter#6]
On export, the following pop-up message is shown: 
The export sheet encountered a run-time error. It probably did not finish the export. The error generated is in the log.

The Log:
```
Export Character to Roll20 1.0.1.10
The export sheet encountered a run-time error. It probably did not finish the export. Here is the error:
Export Character to Roll20: Error: 91: Object reference not set to an instance of an object.
Stack Trace: 
   at ExportToRoll20.ConvertToRoll20Character.GetCharacter(GCACharacter currentCharacter) in c:\Users\noro-gste\AppData\Local\Temp\wubanigp.2.cs:line 170
   at ExportToRoll20.ExportToRoll20.GenerateExport(Party Party, String TargetFilename, SheetOptionsManager Options) in c:\Users\noro-gste\AppData\Local\Temp\wubanigp.0.cs:line 107
   at GCA5.frmMain.Export(ProfileName CurrentProfile, PluginReference CurrentPlugin)
```
I had to switch the library to The basic set then resynchronize, and recalculate, then switch back to Discworld, synchronize and recalculate then it exported. Even with brand new, characters with 0 changes made.

**Comment by MadCoder253** [comment]
I'll need some input from Armin, he might know what is happening. Based on the error, it's before any of the actual export starts.

**Comment by MadCoder253** [comment]
@Ca7iburn Armin figured out the issue and helped me fix the code.  The next version should fix this bug.
